name: Release CD

on:
  workflow_dispatch:
    inputs:
      release_version:
        required: true
        type: string

jobs:
  release_windows_x86:
    name: Windows x86
    runs-on: windows-2022
    env:
      OUTPUT: EndlessSky-win32-${{ inputs.release_version }}.zip
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false
      - name: Setup sccache
        uses: Mozilla-Actions/sccache-action@v0.0.5
      - name: Install x86 MinGW
        run: |
          choco install mingw --forcex86 --force
          echo (Join-Path C: ProgramData mingw64 mingw32 bin) >> $env:GITHUB_PATH
      - uses: lukka/get-cmake@latest
      - uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: 'c82f74667287d3dc386bce81e44964370c91a289'
      - uses: lukka/run-cmake@v10
        with:
          configurePreset: 'mingw32-release'
          buildPreset: 'mingw32-ci-release'
      - name: Package Application
        run: |
          cmake --install build/release
          7z a ${{ env.OUTPUT }} "./install/release/*"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.OUTPUT }}
          path: ${{ env.OUTPUT }}
      - name: Upload Steam Depot
        uses: actions/upload-artifact@v4
        with:
          name: steam-win32-depot
          path: |
            ./install/release/Endless Sky.exe
            ./install/release/*.dll
